[workspace]
members = [ "analog-clock", "colo-rs", "ray-tracer", "sphere-drawing", "virtual-cannon"]
resolver = "2"

[workspace.dependencies]
ray-tracer = { path = "./ray-tracer/" }
colo-rs = { path = "./colo-rs/"}
